global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # collect data directly from the backend application
  - job_name: "backend-book-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["book-app-backend:5001"]
