{
 "title": "Book App Backend Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(flask_http_request_total)" }
   ]
  },
  {
   "title": "Error Rate (5xx) / 5m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "App Uptime Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"backend-book-app\",instance=\"book-app-backend:5001\"}"
    }
   ]
  },
  {
   "title": "Request Duration (Average per route)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[5m]) / rate(flask_http_request_duration_seconds_count[5m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests per Second (by status)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[5m]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  }
 ]
}