apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-app-backend-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: api.book-app.local # Adjust to your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-app-backend
                port:
                  number: 5001
